### ISSUE TITLE
Consider extracting Variant and other types into separate crate.

### ISSUE THREAD

**Issue by iancormac84** [ZerothLaw/mscorlib-safe#6]
Hello! I was searching for any crates that wrapped VARIANT so that I didn't have to roll my own implementation, and I came across this crate. I used it in my project, but that meant compiling way more than I needed, since the only thing I was using was Variant. Would you consider extracting pieces of the crate that are not specific to mscorlib into a separate crate?

**Comment by ZerothLaw** [comment]
Yeah sure! I'll work on that in a bit.

**Comment by iancormac84** [comment]
Thanks!

**Comment by ZerothLaw** [comment]
Hey just wanted to pop in with an update. I've started work on this new crate: https://github.com/ZerothLaw/oaidl-safe

Got Variant and Safearray done, but need to work on BSTR support for completeness. 

In addition, there's a lack of stack unwinding safety as well as unhelpful error messages. Once those three tasks are done, I'll publish it on crates.io.

**Comment by iancormac84** [comment]
Thanks for the update! This surely will be helpful! Feel free to close this issue whenever you're ready!

**Comment by ZerothLaw** [comment]
Okay, BStr and tests done, need to work on documentation, friendly error states, etc. Then I can publish it as a proper crate. :)

**Comment by iancormac84** [comment]
Currently trying to utilize it in my project.

**Comment by ZerothLaw** [comment]
Okay published it! https://docs.rs/oaidl/0.1.4/x86_64-pc-windows-msvc/oaidl/
https://crates.io/crates/oaidl

Let me know how it goes.
